In [46]:
L = [2345, 54, 86478, 697, 782, -8452]
print(L)

[2345, 54, 86478, 697, 782, -8452]


In [48]:
import numpy as np

np.array(L) # Un array solo puede contener un único tipo de datos

array([ 2345,    54, 86478,   697,   782, -8452])

In [50]:
a = np.array(L)
print(a)

[ 2345    54 86478   697   782 -8452]


In [52]:
b = np.array([12, 455, 63.3, True, "abc"])
print(b) # Al poder contener un único tipo de datos convierte todos los elementos a cadena de texto

['12' '455' '63.3' 'True' 'abc']


---

In [54]:
print(L)

[2345, 54, 86478, 697, 782, -8452]


In [56]:
L.pop()

-8452

In [58]:
print(L)

[2345, 54, 86478, 697, 782]


In [63]:
print(a)

[ 2345    54 86478   697   782 -8452]


In [67]:
print(a.mean()) # mean hace la media de los valores

13650.666666666666


---

In [72]:
# Con los arrays no se crea una nueva copia
print(a)
print(a[2:4])

[ 2345    54 86478   697   782 -8452]
[86478   697]


In [74]:
b = a[2:4]
print(b)

[86478   697]


In [76]:
b[:] = 111
print(b)

[111 111]


In [80]:
# Los dos valores de b han sido modificados, pero también los de a
print(a)
print(a[2:4])

[ 2345    54   111   111   782 -8452]
[111 111]


In [86]:
# Para crear una copia que no afecte al array principal usamos .copy()
c = a.copy()
print(c)

[ 2345    54   111   111   782 -8452]


In [84]:
c[0] = 0
print(c)
print(a)

[    0    54   111   111   782 -8452]
[ 2345    54   111   111   782 -8452]
