In [1]:
import numpy as np

mis_datos = np.arange(0, 20)
print(mis_datos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
# De forma predeterminada sigue el orden de filas para rellenar los datos
# matr1 = np.reshape(mis_datos, (5, 4), order = 'C') el siguiente código es el predeterminado
matr1 = np.reshape(mis_datos, (5, 4))
print(matr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
# Seleccionar valor deseado, en este caso será el 9
# Primero el valor de la columa y luego el de la fila, teniendo en cuenta que empiezan en la posición 0 las dos
print(matr1[2, 1])

9


In [11]:
# Con el siguiente código sigue el orden de columnas para rellenar los datos
matr2 = np.reshape(mis_datos, (5, 4), order = 'F')
print(matr2)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [13]:
# Ahora para seleccionar el valor 9
print(matr2[4, 1])

9


---

In [22]:
# Concepto POO
# np.reshape(mis_datos, (5, 4))
print(type(mis_datos))

<class 'numpy.ndarray'>


In [26]:
print(mis_datos.reshape(5, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


---

In [29]:
r1 = ["Soy", "muy", "feliz"]
r2 = ["Que", "gran", "día"]
r3 = [1, 2, 3]

In [35]:
print([r1, r2, r3])

[['Soy', 'muy', 'feliz'], ['Que', 'gran', 'día'], [1, 2, 3]]


In [39]:
print(np.array([r1, r2, r3]))

[['Soy' 'muy' 'feliz']
 ['Que' 'gran' 'día']
 ['1' '2' '3']]


---

In [48]:
dicc1 = {"clave1": "valor1", "clave2": "valor2", "clave3": "valor3"}

In [46]:
# En los diccionarios la forma de acceder a los valores es mediante la clave
# No usaremos print(dicc1[1]) para acceder al valor2
print(dicc1["clave2"])

valor2


In [50]:
dicc2 = {"España": "Valor España", "Francia": 2, "Italia": True}
print(dicc2["España"])
print(dicc2["Italia"])
print(dicc2["Francia"])

Valor España
True
2
