# Numpy arrays

In [2]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4]

In [4]:
# array de una dimensión (vector)
array = np.array(lista)

In [5]:
array

array([1, 2, 3, 4])

In [6]:
lista2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# array de dos dimensiones (matriz)
array2 = np.array(lista2)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy arrays - arange, zeros, ones, linspace, eye

In [9]:
import numpy as np

In [11]:
array = np.arange(5)

In [12]:
array

array([0, 1, 2, 3, 4])

In [13]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(5, 8, 50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy arrays - Números aleatorios - rand y randn

In [24]:
import numpy as np

In [26]:
np.random.rand(5)

array([0.32889771, 0.47485273, 0.25292723, 0.73533667, 0.49501661])

In [27]:
np.random.rand(2, 3)

array([[0.67014696, 0.13882512, 0.00255197],
       [0.21802262, 0.51653531, 0.9323457 ]])

In [28]:
np.random.randn(4)

array([ 0.21255729, -0.96958964, -0.38481856, -0.23673126])

In [29]:
np.random.randn(2, 3)

array([[ 1.20968094,  0.16979585, -0.31959933],
       [ 1.18245695,  1.29361956,  1.0354172 ]])

# Numpy arrays - Números aleatorios enteros - randint

In [30]:
import numpy as np

In [31]:
np.random.randint(1, 20)

13

In [32]:
np.random.randint(1, 20, 5)

array([ 9, 16,  3, 10,  4])

# Numpy arrays - reshape

In [33]:
import numpy as np

In [34]:
array = np.random.randint(1, 100, 25)

In [35]:
array

array([27,  3, 88, 63,  9, 26, 46, 54, 62,  9, 41, 18, 87,  8, 25, 60, 50,
       44, 77, 40, 15, 81, 46, 23, 11])

In [36]:
# Convertir en una matriz, el número de columnas y filas multiplicado debe coincidir en este caso con los 25 elementos.
matriz = array.reshape(5, 5)

In [37]:
matriz

array([[27,  3, 88, 63,  9],
       [26, 46, 54, 62,  9],
       [41, 18, 87,  8, 25],
       [60, 50, 44, 77, 40],
       [15, 81, 46, 23, 11]])

# Numpy arrays - max y min

In [38]:
import numpy as np

In [39]:
array = np.random.randint(1, 100, 50)

In [40]:
array

array([66, 51, 58, 15,  4, 37, 41, 60,  1, 29, 80, 59, 50, 91, 34, 38,  4,
       59, 58,  6, 49, 14, 91, 15, 33, 76, 65, 13,  8, 73, 76, 99, 76, 49,
       11, 31,  2, 80, 78, 16, 88, 91, 10, 78, 72, 60, 75, 22, 86, 31])

In [41]:
valor_maximo = array.max()

In [42]:
valor_maximo

99

In [43]:
posicion_valor_maximo = array.argmax()

In [44]:
posicion_valor_maximo

31

In [45]:
valor_minimo = array.min()

In [46]:
valor_minimo

1

In [47]:
posicion_valor_minimo = array.argmin()

In [48]:
posicion_valor_minimo

8

# Numpy - Indexación en arrays

In [49]:
import numpy as np

In [50]:
array = np.arange(0, 10)

In [51]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
array[9]

9

In [54]:
array[-1]

9

In [55]:
array[2:4]

array([2, 3])

In [56]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
array[5:]

array([5, 6, 7, 8, 9])

In [58]:
array[:5]

array([0, 1, 2, 3, 4])

In [59]:
array2 = array.copy()

In [60]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
array2[0] = 100

In [62]:
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [63]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Numpy - Indexación en arrays de 2 o más dimensiones

In [64]:
import numpy as np

In [65]:
array = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

In [66]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
array[0]

array([1, 2, 3])

In [71]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
array[0, 0]

1

In [74]:
array[1, 1]

5

In [75]:
array[:,0]

array([1, 4, 7])

# Numpy - Seleccionar elementos de un array según una condición

In [76]:
import numpy as np

In [79]:
array = np.arange(0, 10)

In [80]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
condicion = array > 5

In [82]:
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [83]:
array[condicion]

array([6, 7, 8, 9])

In [84]:
array6 = array[condicion]

In [85]:
array6

array([6, 7, 8, 9])

In [86]:
array[array > 5]

array([6, 7, 8, 9])

In [89]:
arraypar = array[array % 2 == 0]

In [90]:
arraypar

array([0, 2, 4, 6, 8])

# Numpy - Operaciones sobre los arrays

In [91]:
import numpy as np

In [92]:
array = np.arange(0, 10)

In [93]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [97]:
array + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [98]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [99]:
array2 = np.arange(5, 15)

In [100]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [103]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [104]:
np.max(array2)

14